# application: chenzelinnet
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates/js
  static_dir: templates/js
- url: /daily
  script: main.app
- url: /upload
  script: main.app
- url: /.*
  script: Register.app


